import type { Metadata } from "next";
import { SubpageHeader } from "@/components/subpage-header";

export const metadata: Metadata = { title: "Terms and Consulting Agreement", robots: { index: false, follow: false } };

export default function TermsPage() {
  return <main className="subpage"><SubpageHeader /><div className="legal-page"><span className="legal-status">Service agreement · Professional review recommended</span><h1>Terms and Consulting Agreement</h1><p className="legal-meta">Version 2026-08-02 · Effective when accepted at checkout</p><article>
    <p>These terms govern services purchased from Jason Sirotin, an independent consultant. By accepting this agreement at checkout, the client confirms that it has authority to enter the agreement and agrees to the plan, payment, cancellation, and working terms below.</p>
    <h2>Service model</h2><p>Services may include planning, research, implementation, troubleshooting, documentation, and improvement of AI-enabled or automated workflows. Each standard plan supports one primary directing stakeholder and one actively prioritized workstream. The relationship is nonexclusive.</p>
    <h2>Plans and payment</h2><ul><li>Guaranteed First Week: $350 paid once, approximately one hour of focused work during a seven-day working period, and no automatic conversion.</li><li>Weekly Partner: $350 billed automatically in advance for each seven-day service period until canceled.</li><li>Monthly Partner: $1,000 billed automatically in advance for each 30-day service period until canceled.</li><li>One-off Work: a separately described deliverable purchased once at the price shown or approved before checkout. One-off work does not renew.</li></ul><p>Approved third-party expenses are additional. Pricing describes available capacity, not a client-facing minute-by-minute timecard.</p>
    <h2>Third-party services and account ownership</h2><p>Whenever practical, hosting, databases, domains, APIs, software, storage, messaging, and similar services will be established in client-owned accounts during a guided setup call. The client enters payment information directly with the provider, pays the provider directly, and retains billing access, credentials, ownership, and administrative control. Jason does not need to receive the client’s card number.</p><p>If the client asks Jason or AutomateMeJay to purchase, pay, or administratively manage a third-party service on the client’s behalf, the client is responsible for the actual approved provider cost plus a convenience charge equal to 25% of that third-party cost. This charge requires advance approval and does not apply when the client owns and pays the provider account directly.</p>
    <h2>First-week money-back guarantee</h2><p>The seven-day guarantee period begins when Jason confirms activation. Before the period ends, the client may choose to continue with a weekly or monthly membership or request a full refund of the $350 first-week service fee. Approved third-party expenses are not included in the refund. The first week never converts automatically; if the client takes no action, work pauses.</p>
    <h2>Cancellation and renewal</h2><p>Weekly and monthly memberships may be canceled at any time through the client membership area or another accepted written channel. Cancellation stops the next automatic renewal. Weekly service remains available through the end of the current paid seven-day period; monthly service remains available through the end of the current paid 30-day period. No additional weekly or monthly membership payment is due after that paid period ends. Except for the Guaranteed First Week money-back guarantee or where required by law, paid membership periods are not prorated or refunded.</p>
    <h2>One-off products and additional work</h2><p>Jason may offer optional one-time products, add-ons, audits, builds, fixes, training, or other scoped deliverables as needs arise. Each one-off item will state or reference its scope and price before payment. Purchasing a one-off item does not start, extend, or renew a weekly or monthly membership unless the checkout clearly says otherwise.</p>
    <h2>Client responsibilities</h2><p>The client supplies timely access and accurate information, tests deliveries, prioritizes requests, approves production use, maintains backups, monitors results, and applies appropriate human review. Meetings, emergency support, 24/7 availability, guaranteed immediate responses, and continuous production monitoring are not included unless separately agreed.</p>
    <h2>Ownership and reuse</h2><p>The client owns its data and paid client-specific deliverables. Jason retains preexisting technology and reusable components, templates, methods, prompts, frameworks, tools, and general know-how. Confidential client information will not be disclosed or reused improperly.</p>
    <h2>No guaranteed outcome</h2><p>Automations require testing and iteration. Results depend on the client’s systems, data, cooperation, third-party services, technical feasibility, and intended use. No particular business outcome, uninterrupted operation, or error-free result is guaranteed.</p>
    <h2>Entire working agreement</h2><p>The plan description shown at checkout, an approved written statement of work for one-off services, and these terms form the working agreement for the purchased service. A written statement of work controls if it expressly conflicts with these standard terms. Professional legal and accounting review is recommended as the service evolves. Questions or cancellation requests may be sent to <a href="mailto:hello@automatemejay.com">hello@automatemejay.com</a>.</p>
  </article></div></main>;
}
