import type { Metadata } from "next";
import { SubpageHeader } from "@/components/subpage-header";

export const metadata: Metadata = { title: "Terms and Consulting Agreement", robots: { index: false, follow: false }, alternates: { canonical: "/legal/terms" } };

export default function TermsPage() {
  return <main className="subpage"><SubpageHeader /><div className="legal-page"><span className="legal-status">Service agreement · Professional review recommended</span><h1>Terms and Consulting Agreement</h1><p className="legal-meta">Version 2026-08-11 · Effective when accepted at checkout</p><article>
    <p>These terms govern services purchased from Jason Sirotin, an independent consultant. By accepting this agreement at checkout, the client confirms that it has authority to enter the agreement and agrees to the plan, payment, cancellation, and working terms below.</p>
    <h2>Service model</h2><p>Services may include planning, research, implementation, troubleshooting, documentation, and improvement of AI-enabled or automated workflows. Each standard plan supports one primary directing stakeholder and one actively prioritized workstream. The relationship is nonexclusive.</p>
    <h2>Plans and payment</h2><ul><li>Free Consultation: one 30-minute discovery and scoping meeting, no card required, no obligation to continue, and no technical working session included.</li><li>Risk-Free First Week: $350 paid once for one seven-day trial period, a full service-fee money-back guarantee, and no automatic conversion.</li><li>Weekly Partner: $350 paid once for one seven-day service period. It does not renew automatically; another week begins only after another payment.</li><li>Monthly Partner: $1,000 billed automatically in advance for each 30-day service period until canceled.</li><li>One-off Work: a separately described deliverable purchased once at the price shown or approved before checkout. One-off work does not renew.</li></ul><p>Only the Risk-Free First Week and Monthly Partner are presented as standard public choices. Weekly and one-off work may be offered privately when the scope calls for them. Approved third-party expenses are additional. The exact included capacity is stated in the applicable SOW, not in public sales copy.</p><p>The Risk-Free First Week, Weekly Partner, and Monthly Partner plans require a plan-specific Statement of Work signed electronically by both the client and Jason Sirotin. The client signs the version presented before Stripe checkout; Jason counter-signs that same version after payment is confirmed. Each party receives access to a printable executed copy.</p>
    <h2>Third-party services and account ownership</h2><p>Whenever practical, hosting, databases, domains, APIs, software, storage, messaging, and similar services will be established in client-owned accounts during a guided setup call. The client enters payment information directly with the provider, pays the provider directly, and retains billing access, credentials, ownership, and administrative control. Jason does not need to receive the client’s card number.</p><p>If the client asks Jason or AutomateMeJay to purchase, pay, or administratively manage a third-party service on the client’s behalf, the client is responsible for the actual approved provider cost plus a convenience charge equal to 25% of that third-party cost. This charge requires advance approval and does not apply when the client owns and pays the provider account directly.</p>
    <h2>Risk-free first-week guarantee</h2><p>The seven-day guarantee period begins when Jason confirms activation. Before the period ends, the client may choose to begin a weekly or monthly engagement, pause, or request a full refund of the $350 first-week consulting service fee. Approved third-party expenses are not included in the refund. The trial never converts automatically; if the client takes no action, work pauses.</p>
    <h2>Cancellation and renewal</h2><p>The risk-free first week does not renew automatically. Weekly service also does not renew automatically, so the client simply does not purchase another week. Monthly membership may be canceled at any time through the client membership area or another accepted written channel, including during the first week of a monthly period. Cancellation stops the next automatic renewal, but it does not shorten the current period or create a prorated refund. Monthly service remains available through the end of the current paid 30-day period. Except for the Risk-Free First Week money-back guarantee or where required by law, paid service periods are not prorated or refunded.</p>
    <h2>One-off products and optional additions</h2><p>Jason may offer a separately approved product, add-on, audit, build, fix, training engagement, or other scoped deliverable when needed. Each item will state or reference its scope and price before payment. An optional addition does not create, extend, or renew a weekly or monthly engagement unless the written checkout terms clearly say otherwise.</p>
    <h2>Client responsibilities</h2><p>The client supplies timely access and accurate information, tests deliveries, prioritizes requests, approves production use, maintains backups, monitors results, and applies appropriate human review. Meetings, emergency support, 24/7 availability, guaranteed immediate responses, and continuous production monitoring are not included unless separately agreed.</p>
    <h2>Ownership and reuse</h2><p>The client owns its data and paid client-specific deliverables. Jason retains preexisting technology and reusable components, templates, methods, prompts, frameworks, tools, and general know-how. Confidential client information will not be disclosed or reused improperly.</p>
    <h2>No guaranteed outcome</h2><p>Automations require testing and iteration. Results depend on the client’s systems, data, cooperation, third-party services, technical feasibility, and intended use. No particular business outcome, uninterrupted operation, or error-free result is guaranteed.</p>
    <h2>Electronic signatures and records</h2><p>The parties agree that typed names and recorded electronic actions may serve as signatures when the signer affirmatively consents and intends to sign. SOWs may be signed in counterparts. The service preserves the SOW version, document hash, signer names, timestamps, payment linkage, and executed electronic copy. A signer who does not wish to transact electronically should contact <a href="mailto:hello@automatemejay.com">hello@automatemejay.com</a> before purchase to request a paper process.</p>
    <h2>Entire working agreement</h2><p>The plan description shown at checkout, the applicable signed Statement of Work, an approved written statement of work for one-off services, and these terms form the working agreement for the purchased service. A signed SOW controls only where it expressly conflicts with these standard terms. Professional legal and accounting review is recommended as the service evolves. Questions or cancellation requests may be sent to <a href="mailto:hello@automatemejay.com">hello@automatemejay.com</a>.</p>
  </article></div></main>;
}
