-- Production hardening: fail closed for public writes, make future Data API
-- exposure opt-in, preserve an append-only security audit trail, and tighten
-- integrity checks on client-authored records.

create table public.security_events (
  id bigint generated by default as identity primary key,
  request_id text not null check (length(request_id) between 8 and 128),
  event_type text not null check (length(event_type) between 3 and 100),
  route text not null check (length(route) between 3 and 100),
  severity text not null default 'info' check (severity in ('info', 'warning', 'critical')),
  request_key_hash text not null check (length(request_key_hash) = 64),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index security_events_rate_limit_idx
  on public.security_events (route, request_key_hash, event_type, created_at desc);
create index security_events_created_idx
  on public.security_events (created_at desc);

alter table public.security_events enable row level security;
revoke all on public.security_events from public, anon, authenticated;
grant select, insert, delete on public.security_events to service_role;
grant usage, select on sequence public.security_events_id_seq to service_role;

create policy "security_events_service_role_only"
on public.security_events for all to service_role
using (true) with check (true);

-- Public intake now enters through the rate-limited server route only.
drop policy if exists "intake_public_insert" on public.intake_requests;
revoke insert on public.intake_requests from anon, authenticated;

-- Keep the existing database trigger as a second layer against repeated email
-- submissions, including any future server integration that bypasses the app.
create or replace function private.limit_intake_rate()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  recent_requests integer;
begin
  select count(*) into recent_requests
  from public.intake_requests
  where lower(email) = lower(new.email)
    and created_at > now() - interval '1 hour';

  if recent_requests >= 5 then
    raise exception 'Too many recent intake requests.' using errcode = 'P0001';
  end if;

  return new;
end;
$$;

revoke all on function private.limit_intake_rate() from public, anon, authenticated;

-- Clients may request a cost authorization, but they cannot self-approve it or
-- claim that another user approved it.
drop policy if exists "costs_insert_members" on public.cost_authorizations;
create policy "costs_insert_members"
on public.cost_authorizations for insert to authenticated
with check (
  private.is_workspace_member(workspace_id)
  and status = 'requested'
  and approved_by is null
  and approved_at is null
);

-- A reply may only point to a message in the same authorized workspace.
drop policy if exists "messages_insert_self" on public.messages;
create policy "messages_insert_self"
on public.messages for insert to authenticated
with check (
  sender_id = (select auth.uid())
  and private.is_workspace_member(workspace_id)
  and (
    parent_message_id is null
    or exists (
      select 1 from public.messages parent
      where parent.id = parent_message_id
        and parent.workspace_id = workspace_id
        and private.is_workspace_member(parent.workspace_id)
    )
  )
);

-- Storage upserts need UPDATE in addition to SELECT and INSERT. Restrict
-- replacement to the original owner inside an organization they still belong to.
create policy "client_files_update_own"
on storage.objects for update to authenticated
using (
  bucket_id = 'client-files'
  and owner_id = (select auth.uid()::text)
  and private.is_org_member(((storage.foldername(name))[1])::uuid)
)
with check (
  bucket_id = 'client-files'
  and owner_id = (select auth.uid()::text)
  and private.is_org_member(((storage.foldername(name))[1])::uuid)
);

-- Server-only tables intentionally have no client grants. Explicit service-role
-- policies document that model and keep the security advisor quiet.
create policy "agent_action_audit_service_role_only"
on public.agent_action_audit for all to service_role using (true) with check (true);
create policy "guarantee_decisions_service_role_only"
on public.guarantee_decisions for all to service_role using (true) with check (true);
create policy "guaranteed_engagements_service_role_only"
on public.guaranteed_engagements for all to service_role using (true) with check (true);

-- Existing public RPC surface is not used by this application.
revoke execute on all functions in schema public from public, anon, authenticated;

-- Make every future object in the exposed public schema opt-in. Apply this to
-- the project-owned postgres role. Supabase-managed roles cannot be altered by
-- project connections; current objects owned by those roles remain protected by
-- their platform defaults and RLS.
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public, anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;
